export const QUIZ_STEPS = [
  {
    id:"role", type:"multi", emoji:"💼",
    q:"What do you use your desk for?",
    hint:"Select all that apply",
    opts:[
      {v:"Development / Coding",   e:"💻", d:"IDEs, terminals, multiple screens"},
      {v:"Design / Video Editing", e:"🎨", d:"Color accuracy is critical"},
      {v:"Writing / Research",     e:"📝", d:"Long deep-focus sessions"},
      {v:"Video Calls / Meetings", e:"📹", d:"Camera & audio always on"},
      {v:"Gaming",                 e:"🎮", d:"High refresh, low latency"},
      {v:"Study / Online Classes", e:"📚", d:"Eye care & focus setup"},
      {v:"Content Creation",       e:"🎙️", d:"Mic, lighting, backdrop"},
      {v:"Trading / Finance",      e:"📊", d:"Multi-monitor, live data"},
    ],
  },
  {
    id:"budget", type:"budget", emoji:"💰",
    q:"What's your total budget?",
    hint:"Type any amount — AI respects it to the rupee",
    min:3000, max:500000, step:500, def:30000,
    presets:[
      {l:"Basic",   v:10000,  e:"🌱"},
      {l:"Starter", v:25000,  e:"⚡"},
      {l:"Solid",   v:50000,  e:"🔥"},
      {l:"Premium", v:100000, e:"💎"},
      {l:"Pro",     v:200000, e:"👑"},
    ],
  },
  {
    id:"hours", type:"slider", emoji:"⏱️",
    q:"Hours per day at your desk?",
    hint:"This drives how much we prioritise ergonomics",
    min:1, max:16, def:6,
  },
  {
    id:"existing", type:"multi", emoji:"✅",
    q:"What do you already own?",
    hint:"We'll skip these — budget goes only to what's missing",
    opts:[
      {v:"Laptop / PC",           e:"💻", d:"Primary device"},
      {v:"Monitor",               e:"🖥️", d:"External display"},
      {v:"Desk",                  e:"🗄️", d:"Work surface"},
      {v:"Chair",                 e:"🪑", d:"Seating"},
      {v:"Keyboard & Mouse",      e:"⌨️", d:"Input devices"},
      {v:"Headphones",            e:"🎧", d:"Audio"},
      {v:"Webcam",                e:"📷", d:"Video calls"},
      {v:"Nothing — fresh start", e:"🆕", d:"Build from zero", excl:true},
    ],
  },
  {
    id:"room", type:"card", emoji:"🏠",
    q:"How big is your workspace?",
    hint:"Affects desk size, monitor arm, and layout picks",
    opts:[
      {v:"Tiny corner",        s:"< 50 sq ft",    e:"📐", d:"Space-saving only"},
      {v:"Small room",         s:"50–100 sq ft",  e:"🏠", d:"Compact but complete"},
      {v:"Medium room",        s:"100–200 sq ft", e:"🏡", d:"Full setup fits"},
      {v:"Large / dedicated",  s:"200+ sq ft",    e:"🏢", d:"No constraints"},
    ],
  },
  {
    id:"lighting", type:"card", emoji:"☀️",
    q:"Natural lighting situation?",
    hint:"We plan your artificial lighting around this",
    opts:[
      {v:"Dark room",        s:"No windows",          e:"🌑", d:"Bias lighting essential"},
      {v:"Dim",              s:"One small window",    e:"🌤️", d:"Desk lamp important"},
      {v:"Good with glare",  s:"Window causes glare", e:"😎", d:"Anti-glare monitor"},
      {v:"Bright all day",   s:"Well-lit space",      e:"☀️", d:"Less lighting gear"},
    ],
  },
  {
    id:"pain", type:"multi", emoji:"😤",
    q:"What problems are you facing?",
    hint:"Every single one gets specifically addressed",
    opts:[
      {v:"Eye strain / headaches",    e:"👁️", d:"Monitor + lighting fix"},
      {v:"Back or neck pain",         e:"🦴", d:"Chair + monitor height"},
      {v:"Wrist / arm fatigue",       e:"🖐️", d:"Keyboard angle + rest"},
      {v:"Slow or unstable internet", e:"🌐", d:"WiFi extender / ethernet"},
      {v:"Bad audio on calls",        e:"🎙️", d:"Dedicated mic or headset"},
      {v:"Cluttered messy desk",      e:"🗂️", d:"Organizers + cable mgmt"},
      {v:"Poor video on calls",       e:"📷", d:"Webcam + ring light"},
      {v:"Gets too hot",              e:"🥵", d:"Desk fan + tips"},
    ],
  },
  {
    id:"priority", type:"rank", emoji:"🎯",
    q:"Rank your priorities",
    hint:"Drag to reorder — #1 gets the biggest budget share",
    opts:[
      {v:"Ergonomics & comfort", e:"🪑"},
      {v:"Display quality",      e:"🖥️"},
      {v:"Productivity & speed", e:"⚡"},
      {v:"Aesthetics & vibe",    e:"✨"},
      {v:"Audio quality",        e:"🔊"},
      {v:"Clean organisation",   e:"🧹"},
    ],
  },
  {
    id:"vibe", type:"vibe", emoji:"🎨",
    q:"Choose your aesthetic",
    hint:"Products, colors and style will match this",
    opts:[
      {v:"Clean Minimal",      s:"White · Beige · Neutral",  e:"🤍", bg:"#faf7f2", ac:"#c4a882"},
      {v:"Dark Battlestation", s:"Black · RGB · Dramatic",   e:"🖤", bg:"#0d0d1a", ac:"#00d4ff"},
      {v:"Warm & Cozy",        s:"Wood · Amber · Natural",   e:"🪵", bg:"#2a1a0a", ac:"#f59e0b"},
      {v:"Pro Corporate",      s:"Gray · Sleek · Minimal",   e:"💼", bg:"#1a2030", ac:"#64748b"},
      {v:"Aesthetic/Pinterest",s:"Plants · Pastel · Dreamy", e:"🌿", bg:"#0f1f10", ac:"#86efac"},
      {v:"Surprise me!",       s:"AI picks the best fit",    e:"🎲", bg:"#1a0a2a", ac:"#a78bfa"},
    ],
  },
  {
    id:"extras", type:"multi", emoji:"⚙️",
    q:"Any special requirements?",
    hint:"Optional — helps us go beyond the obvious",
    opts:[
      {v:"Wireless everything",    e:"📡", d:"Zero cable clutter"},
      {v:"Need power backup (UPS)",e:"🔋", d:"For outages & surges"},
      {v:"Space is very limited",  e:"📦", d:"Compact form factors"},
      {v:"Pet-friendly setup",     e:"🐾", d:"Extra cable management"},
      {v:"Shared / family space",  e:"👨‍👩‍👧", d:"Noise-cancelling priority"},
      {v:"Travel often",           e:"✈️", d:"Portable accessories"},
      {v:"Want EMI options",       e:"💳", d:"We'll flag EMI items"},
      {v:"No special needs",       e:"👍", d:"", excl:true},
    ],
  },
];

export const GEN_MSGS = [
  "Reading your profile…",
  "Allocating budget across categories…",
  "Sourcing 2026 Indian market products…",
  "Solving every pain point…",
  "Matching your aesthetic…",
  "Finalising setup…",
];